spring:
  datasource:
    url: jdbc:mariadb://192.0.3.47:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: osj
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace